%Here insert the image name you want to process
I = imread("Cell_01_Actin.tif");
[counts, binLocations] = imhist(I);
imhist(I);
imshow(I,[]);
I_eq = histeq(I);
denoisedFrame = medfilt2(I_eq, [5,5]);
I_bw = imbinarize(denoisedFrame,'adaptive');
se90 = strel('line',3,90);
se0 = strel('line',3,0);
I_fill = edge(I_bw);
imshow(I_eq,[]);
[~,threshold] = edge(I_eq,'sobel');
fudgeFactor = 0.5;
BWs = edge(I_eq,'sobel',threshold * fudgeFactor);
se90 = strel('line',8,90);
se0 = strel('line',8,0);
BWsdil = imdilate(BWs,[se90 se0]);
test = bwareaopen(~BWsdil,300, 8);
test = imclearborder(test);
denoisedFrame = medfilt2(BWsdil, [5,5]);
imshow(test,[]);
I_eq(~test) = 0;
I_test = histeq(I_eq);
I_Cell = mat2gray(I_test);
imshow(I_Cell, []);
figure(2);
imhist(I_Cell);
imwrite(I_Cell, ['Cell_01_Actin_pp.tif']);
